### ISSUE TITLE
Composer Fehler

### ISSUE THREAD

**Issue by fluxdw** [fluxapps/DhbwTraining#5]
Building Static Artifacts for ILIAS
===================================
 
PHP Fatal error:  Trait 'srag\DIC\DhbwTraining\DICTrait' not found in /srv/www/ilias/awz/teststudi/Customizing/global/plugins/Services/Repository/RepositoryObject/DhbwTraining/classes/Recommender/RecommenderCurl.php on line 13
Script @php setup/cli.php build-artifacts --yes handling the post-autoload-dump event returned with error code 255

**Comment by mstuder** [comment]
Liebe Dhouha

Wir könnten den Composer Fehler bei uns nicht nachstellen. Setzt du denn "bereits" composer 2 ein? Konkret, welche Version setzt du ein?

An und für sich, braucht es in diesem Plugin kein Composer, da vendor ja im Repository liegen. Ich würde euch zudem empfehlen, dass ihr prüft ob ihr bei ILIAS nicht jeweils auf die bereitgestellten ZIP-Versionen setzten möchtet. Denn hier sind die Abhängikeiten bereits mit dabei. Sowei ich informiert bin, wird ILIAS künftig auch die npm-Module nicht mehr in den sourcen von github mitführen. Spätestens ab dann, ist m.E. die Wahl des bereitgestellten ZIP-Paketes die bessere Wahl, als die Abhängigkeiten eigenständig zu laden.

Liebe Grüsse
Martin
